# Generated by Django 5.1.2 on 2024-11-15 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_replace_nationality_with_department'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='residencepermitfeedback',
            options={'ordering': ['-modification_date']},
        ),
    ]
