# Generated by Django 5.2.1 on 2025-05-21 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0008_remove_healthinsurancequestion_income_over_limit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthinsurancequestion',
            name='is_married',
            field=models.BooleanField(null=True),
        ),
    ]
