# Generated by Django 5.2.1 on 2025-05-21 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0009_healthinsurancequestion_is_married'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthinsurancequestion',
            name='occupation',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
