# Generated by Django 5.2.4 on 2025-07-07 11:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("forms", "0010_alter_healthinsurancequestion_occupation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="healthinsurancequestion",
            name="phone",
        ),
    ]
