# Generated by Django 5.2.5 on 2025-09-01 12:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("forms", "0013_migrate_to_insurance"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pensionrefundquestion",
            options={},
        ),
    ]
