# Generated by Django 5.2.8 on 2025-12-02 13:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("forms", "0021_remove_citizenshipfeedbackreminder_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="residencepermitfeedback",
            name="health_insurance_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PUBLIC", "Public health insurance"),
                    ("PRIVATE", "Private health insurance"),
                    ("EXPAT", "Expat health insurance"),
                    ("FAMILY", "Familienversicherung"),
                    ("EHIC", "EHIC"),
                    ("OTHER", "Other"),
                    ("", "Unknown"),
                ],
                default="",
                max_length=20,
            ),
        ),
    ]
