# Generated by Django 5.2.8 on 2025-12-02 14:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("forms", "0022_alter_residencepermitfeedback_health_insurance_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="residencepermitfeedback",
            name="health_insurance_notes",
        ),
        migrations.AddField(
            model_name="residencepermitfeedback",
            name="health_insurance_name",
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
