# Generated by Django 5.2.8 on 2025-12-02 17:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("forms", "0023_remove_residencepermitfeedback_health_insurance_notes_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="residencepermitfeedback",
            name="validity_in_months",
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True),
        ),
    ]
