# Generated by Django 5.2.4 on 2025-08-11 21:41

import django.db.models.deletion
import django_countries.fields
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('whatsapp', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(blank=True, help_text='For example, "health insurance for a Blue Card"', max_length=150)),
                ('notes', models.TextField(blank=True, help_text='For future notes, add Updates to the Case.', verbose_name='Initial notes')),
                ('referrer', models.CharField(blank=True, help_text='Part of the commissions will be paid out to that referrer')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField(blank=True)),
                ('file', models.FileField(blank=True, upload_to='attachments/', verbose_name='Attachment')),
                ('status', models.CharField(blank=True, choices=[('new', 'New'), ('in_progress', 'In consultation'), ('waiting_client', 'Waiting for client'), ('waiting_insurer', 'Waiting for insurer'), ('accepted', 'Accepted by insurer'), ('rejected', 'Rejected'), ('resolved', 'Generic solution offered'), ('stale', 'Abandoned')], max_length=20)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Update',
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='InsuredPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, help_text='For example "Spouse"', max_length=250)),
                ('occupation', models.CharField(blank=True, max_length=50)),
                ('nationality', django_countries.fields.CountryField(blank=True, max_length=2)),
                ('country_of_residence', django_countries.fields.CountryField(blank=True, max_length=2)),
                ('age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insurance.case')),
            ],
            options={
                'verbose_name': 'Insured person',
                'ordering': ['first_name', 'last_name'],
            },
        ),
        migrations.CreateModel(
            name='Outcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insurance_type', models.CharField(choices=[('disability', 'Disability insurance'), ('health_expat', 'Health insurance - Incoming'), ('health_private', 'Health insurance - Private'), ('health_public', 'Health insurance - Public'), ('health_travel', 'Health insurance - Travel'), ('health_zusatz', 'Health insurance - Supplementary'), ('legal', 'Legal insurance'), ('liability', 'Liability insurance'), ('other', 'Other')], max_length=20)),
                ('provider', models.CharField(help_text='For example, "Ottonova"', max_length=100)),
                ('policy', models.CharField(help_text='For example, "Expat Student Plus"', max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('date_start', models.DateField(help_text='When the policy begins')),
                ('date_end', models.DateField(blank=True, help_text='When the policy ends, if applicable', null=True)),
                ('commission_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total commission amount')),
                ('commission_received_date', models.DateField(blank=True, null=True, verbose_name='Insurer commission paid on')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outcomes', to='insurance.case')),
            ],
            options={
                'verbose_name': 'Outcome',
            },
        ),
    ]
