# Generated by Django 5.2.4 on 2025-08-12 15:58

import django.db.models.deletion
import django.utils.timezone
import django_countries.fields
import forms.utils
import insurance.models
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('whatsapp', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(blank=True, help_text='For example, "health insurance for a Blue Card"', max_length=150)),
                ('notes', models.TextField(blank=True, help_text='For future notes, add Updates to the Case.', verbose_name='Initial notes')),
                ('referrer', models.CharField(blank=True, help_text='Part of the commissions will be paid out to that referrer')),
                ('status', models.CharField(choices=[('NEW', 'New'), ('IN_PROGRESS', 'In consultation'), ('WAITING_CLIENT', 'Waiting for client'), ('WAITING_INSURER', 'Waiting for insurer'), ('ACCEPTED', 'Accepted by insurer'), ('REJECTED', 'Rejected'), ('RESOLVED', 'Other solution'), ('STALE', 'Stale')], default='new', editable=False, max_length=20)),
            ],
            options={
                'ordering': ['-creation_date'],
            },
        ),
        migrations.CreateModel(
            name='BrokerNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('delivery_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Scheduled'), (1, 'Error'), (2, 'Sent'), (3, 'Sent and redacted for privacy')], default=0)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insurance.case')),
            ],
            options={
                'ordering': ['-creation_date'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('file', models.FileField(blank=True, upload_to='attachments/', verbose_name='Attachment')),
                ('status', models.CharField(blank=True, choices=[('NEW', 'New'), ('IN_PROGRESS', 'In consultation'), ('WAITING_CLIENT', 'Waiting for client'), ('WAITING_INSURER', 'Waiting for insurer'), ('ACCEPTED', 'Accepted by insurer'), ('REJECTED', 'Rejected'), ('RESOLVED', 'Other solution'), ('STALE', 'Stale')], max_length=20)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', related_query_name='comment', to='insurance.case')),
            ],
            options={
                'verbose_name': 'Update',
                'ordering': ['-creation_date'],
            },
        ),
        migrations.CreateModel(
            name='CustomerNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, validators=[forms.utils.validate_email])),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('delivery_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Scheduled'), (1, 'Error'), (2, 'Sent'), (3, 'Sent and redacted for privacy')], default=0)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insurance.case')),
            ],
            options={
                'ordering': ['-creation_date'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FeedbackNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Scheduled'), (1, 'Error'), (2, 'Sent'), (3, 'Sent and redacted for privacy')], default=0)),
                ('delivery_date', models.DateTimeField(default=insurance.models.in_1_week)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insurance.case')),
            ],
            options={
                'ordering': ['-creation_date'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InsuredPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('description', models.CharField(blank=True, help_text='For example "Spouse"', max_length=250)),
                ('occupation', models.CharField(blank=True, max_length=50)),
                ('income', models.PositiveIntegerField(blank=True, null=True, verbose_name='Yearly income')),
                ('nationality', django_countries.fields.CountryField(blank=True, max_length=2)),
                ('country_of_residence', django_countries.fields.CountryField(blank=True, max_length=2)),
                ('is_married', models.BooleanField(null=True)),
                ('age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insured_persons', related_query_name='insured_person', to='insurance.case')),
            ],
            options={
                'verbose_name': 'Insured person',
            },
        ),
        migrations.CreateModel(
            name='Outcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insurance_type', models.CharField(choices=[('disability', 'Disability insurance'), ('health_expat', 'Health insurance - Incoming'), ('health_private', 'Health insurance - Private'), ('health_public', 'Health insurance - Public'), ('health_travel', 'Health insurance - Travel'), ('health_zusatz', 'Health insurance - Supplementary'), ('legal', 'Legal insurance'), ('liability', 'Liability insurance'), ('other', 'Other')], max_length=20)),
                ('provider', models.CharField(help_text='For example, "Ottonova"', max_length=100)),
                ('policy', models.CharField(help_text='For example, "Expat Student Plus"', max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('date_start', models.DateField(help_text='When the policy begins')),
                ('date_end', models.DateField(blank=True, help_text='When the policy ends, if applicable', null=True)),
                ('commission_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total commission amount')),
                ('commission_received_date', models.DateField(blank=True, null=True, verbose_name='Insurer commission paid on')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outcomes', to='insurance.case')),
            ],
            options={
                'verbose_name': 'Outcome',
            },
        ),
    ]
