# Generated by Django 5.2.4 on 2025-08-07 11:14

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('whatsapp', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField(blank=True)),
                ('file', models.FileField(blank=True, upload_to='attachments/', verbose_name='Attachment')),
                ('status', models.CharField(blank=True, choices=[('new', 'New'), ('in_progress', 'In consultation'), ('waiting_client', 'Waiting for client'), ('waiting_insurer', 'Waiting for insurer'), ('accepted', 'Accepted by insurer'), ('rejected', 'Rejected'), ('resolved', 'Generic solution offered'), ('stale', 'Abandoned')], max_length=20)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to='insurance.customer')),
            ],
            options={
                'verbose_name': 'Update',
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(help_text='For example, "health insurance for a Blue Card"', max_length=150)),
                ('description', models.TextField(blank=True)),
                ('referrer', models.CharField(blank=True, help_text='Part of the commissions will be paid out to that referrer')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='insurance.customer')),
            ],
        ),
        migrations.CreateModel(
            name='InsuredPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('date_of_birth', models.DateField()),
                ('nationality', models.CharField(max_length=100)),
                ('country_of_residence', models.CharField(max_length=100)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insurance.customer')),
            ],
            options={
                'ordering': ['first_name', 'last_name'],
            },
        ),
        migrations.CreateModel(
            name='CaseInsuredPersons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insurance.case')),
                ('insured_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insurance.insuredperson')),
            ],
        ),
        migrations.AddField(
            model_name='case',
            name='insured_persons',
            field=models.ManyToManyField(related_name='cases', through='insurance.CaseInsuredPersons', to='insurance.insuredperson'),
        ),
        migrations.CreateModel(
            name='Outcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insurance_type', models.CharField(choices=[('disability', 'Disability insurance'), ('health_expat', 'Health insurance - Incoming'), ('health_private', 'Health insurance - Private'), ('health_public', 'Health insurance - Public'), ('health_travel', 'Health insurance - Travel'), ('health_zusatz', 'Health insurance - Supplementary'), ('legal', 'Legal insurance'), ('liability', 'Liability insurance'), ('other', 'Other')], max_length=20)),
                ('provider', models.CharField(help_text='For example, "Ottonova"', max_length=100)),
                ('policy', models.CharField(help_text='For example, "Expat Student Plus"', max_length=100)),
                ('date_start', models.DateField(help_text='When the policy begins')),
                ('date_end', models.DateField(help_text='When the policy ends, if applicable', null=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outcomes', to='insurance.case')),
            ],
        ),
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('frequency', models.CharField(choices=[('once', 'Once'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], max_length=10)),
                ('date_start', models.DateField()),
                ('date_end', models.DateField(null=True)),
                ('outcome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='insurance.outcome')),
            ],
            options={
                'verbose_name': 'Commission payment',
            },
        ),
    ]
