# Generated by Django 5.2.4 on 2025-08-07 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commission',
            name='date_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='outcome',
            name='date_end',
            field=models.DateField(blank=True, help_text='When the policy ends, if applicable', null=True),
        ),
    ]
