# Generated by Django 5.2.4 on 2025-08-12 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('IN_PROGRESS', 'In consultation'), ('WAITING_CLIENT', 'Waiting for client'), ('WAITING_INSURER', 'Waiting for insurer'), ('ACCEPTED', 'Accepted by insurer'), ('REJECTED', 'Rejected'), ('RESOLVED', 'Other solution found'), ('STALE', 'Stale')], default='NEW', editable=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='comment',
            name='status',
            field=models.CharField(blank=True, choices=[('NEW', 'New'), ('IN_PROGRESS', 'In consultation'), ('WAITING_CLIENT', 'Waiting for client'), ('WAITING_INSURER', 'Waiting for insurer'), ('ACCEPTED', 'Accepted by insurer'), ('REJECTED', 'Rejected'), ('RESOLVED', 'Other solution found'), ('STALE', 'Stale')], max_length=20),
        ),
    ]
