# Generated by Django 5.2.5 on 2025-08-13 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0002_alter_case_status_alter_comment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='case',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
