# Generated by Django 5.2.5 on 2025-08-18 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0003_alter_case_phone_alter_case_whatsapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='contact_method',
            field=models.CharField(choices=[('EMAIL', 'Email'), ('WHATSAPP', 'WhatsApp')], default='EMAIL', max_length=15, verbose_name='Preferred contact method'),
        ),
    ]
