# Generated by Django 5.2.5 on 2025-08-18 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0004_case_contact_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='title',
        ),
    ]
