# Generated by Django 5.2.5 on 2025-08-18 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0005_remove_case_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insuredperson',
            name='occupation',
            field=models.CharField(choices=[('employee', 'Employee'), ('azubi', 'Azubi'), ('studentEmployee', 'Student (working)'), ('studentSelfEmployed', 'Student (self-employed)'), ('studentUnemployed', 'Student (unemployed)'), ('selfEmployed', 'Self-employed'), ('unemployed', 'Unemployed'), ('other', 'Other/unknown')], default='other', max_length=50),
        ),
    ]
