# Generated by Django 5.2.6 on 2025-10-03 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0009_remove_case_phone_remove_case_whatsapp_case_age_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='case',
            options={'ordering': ['-creation_date'], 'verbose_name': 'Insurance case'},
        ),
    ]
