# Generated by Django 5.2.7 on 2025-10-03 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Monitor",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("key", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Update",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("creation_date", models.DateTimeField(auto_now_add=True)),
                ("status", models.IntegerField(choices=[(20, "INFO"), (30, "WARNING"), (40, "ERROR")])),
                ("message", models.TextField(blank=True, null=True)),
                (
                    "monitor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="updates", to="management.monitor"
                    ),
                ),
            ],
            options={
                "ordering": ["-creation_date"],
            },
        ),
    ]
