# Generated by Django 5.2.7 on 2025-10-06 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monitor',
            options={'ordering': ['name', 'key']},
        ),
    ]
