# Generated by Django 5.1.2 on 2024-10-22 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PensionRefundQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Scheduled'), (1, 'Error'), (2, 'Sent')])),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('nationality', models.CharField(max_length=2)),
                ('country_of_residence', models.CharField(max_length=2)),
                ('question', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
