# Generated by Django 5.1.2 on 2024-10-23 16:53

import django.utils.timezone
import django_countries.fields
import forms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HealthInsuranceQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('delivery_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Scheduled'), (1, 'Error'), (2, 'Sent'), (3, 'Sent and redacted for privacy')], default=0)),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('income_over_limit', models.BooleanField()),
                ('occupation', models.CharField(max_length=50)),
                ('age', models.PositiveSmallIntegerField()),
                ('question', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HealthInsuranceQuestionConfirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('delivery_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Scheduled'), (1, 'Error'), (2, 'Sent'), (3, 'Sent and redacted for privacy')], default=0)),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PensionRefundQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('delivery_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Scheduled'), (1, 'Error'), (2, 'Sent'), (3, 'Sent and redacted for privacy')], default=0)),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('nationality', django_countries.fields.CountryField(max_length=2)),
                ('country_of_residence', django_countries.fields.CountryField(max_length=2)),
                ('question', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PensionRefundReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('delivery_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Scheduled'), (1, 'Error'), (2, 'Sent'), (3, 'Sent and redacted for privacy')], default=0)),
                ('email', models.EmailField(max_length=254)),
                ('refund_amount', models.PositiveIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PensionRefundRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('delivery_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Scheduled'), (1, 'Error'), (2, 'Sent'), (3, 'Sent and redacted for privacy')], default=0)),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('nationality', django_countries.fields.CountryField(max_length=2)),
                ('country_of_residence', django_countries.fields.CountryField(max_length=2)),
                ('arrival_date', models.DateField()),
                ('departure_date', models.DateField()),
                ('birth_date', models.DateField()),
                ('partner', models.CharField(choices=[('fundsback', 'partner@fundsback.org'), ('germanypensionrefund', 'refund@germanypensionrefund.com'), ('pensionrefundgermany', 'support@pension-refund.com')], max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TaxIdRequestFeedbackReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Scheduled'), (1, 'Error'), (2, 'Sent'), (3, 'Sent and redacted for privacy')], default=0)),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=150)),
                ('delivery_date', models.DateTimeField(default=forms.models.in_8_weeks)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
