# Generated by Django 5.1.2 on 2024-10-22 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pensionrefundquestion',
            name='country_of_residence',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='pensionrefundquestion',
            name='nationality',
            field=models.CharField(max_length=150),
        ),
    ]
