# Generated by Django 5.1.2 on 2024-10-22 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_alter_pensionrefundquestion_country_of_residence_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pensionrefundquestion',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Scheduled'), (1, 'Error'), (2, 'Sent')], default=0),
        ),
    ]
