# Generated by Django 5.1.2 on 2024-10-23 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_alter_pensionrefundquestion_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthInsuranceQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Scheduled'), (1, 'Error'), (2, 'Sent'), (3, 'Sent and redacted for privacy')], default=0)),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('income_over_limit', models.BooleanField()),
                ('occupation', models.CharField(max_length=50)),
                ('age', models.PositiveSmallIntegerField()),
                ('question', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
