# Generated by Django 5.1.2 on 2024-10-23 12:05

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_healthinsurancequestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='PensionRefundRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Scheduled'), (1, 'Error'), (2, 'Sent'), (3, 'Sent and redacted for privacy')], default=0)),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('nationality', django_countries.fields.CountryField(max_length=2)),
                ('country_of_residence', django_countries.fields.CountryField(max_length=2)),
                ('arrival_date', models.DateField()),
                ('departure_date', models.DateField()),
                ('birth_date', models.DateField()),
                ('partner', models.CharField(choices=[('fundsback', 'partner@fundsback.org'), ('germanypensionrefund', 'refund@germanypensionrefund.com'), ('pensionrefundgermany', 'support@pension-refund.com')], max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
