# Generated by Django 5.1.2 on 2024-10-22 21:00

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_alter_pensionrefundquestion_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pensionrefundquestion',
            name='country_of_residence',
            field=django_countries.fields.CountryField(max_length=2),
        ),
        migrations.AlterField(
            model_name='pensionrefundquestion',
            name='nationality',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
