# Generated by Django 5.1.2 on 2024-10-23 12:54

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0004_pensionrefundrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('delivery_date', models.DateTimeField(default=datetime.datetime.now)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Scheduled'), (1, 'Error'), (2, 'Sent'), (3, 'Sent and redacted for privacy')], default=0)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='healthinsurancequestion',
            name='delivery_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='pensionrefundquestion',
            name='delivery_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='pensionrefundrequest',
            name='delivery_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.CreateModel(
            name='PensionRefundReminder',
            fields=[
                ('scheduledreminder_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='forms.scheduledreminder')),
                ('eligibility_date', models.DateField()),
                ('refund_amount', models.PositiveIntegerField()),
            ],
            options={
                'abstract': False,
            },
            bases=('forms.scheduledreminder',),
        ),
    ]
