# Generated by Django 5.1.2 on 2024-10-23 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0005_scheduledreminder_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pensionrefundreminder',
            name='eligibility_date',
        ),
    ]
