# Generated by Django 5.2.6 on 2025-10-01 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0017_alter_citizenshipfeedback_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residencepermitfeedback',
            name='department',
            field=models.CharField(choices=[('A1_A5', 'A1, A5'), ('A2_A3_A4', 'A2, A3, A4'), ('B1_B2_B3_B4', 'B1, B2, B3, B4'), ('B6', 'B6'), ('E1', 'E1'), ('E2', 'E2'), ('E3', 'E3'), ('E4', 'E4'), ('E5', 'E5'), ('E6', 'E6'), ('M1', 'M1'), ('M2', 'M2'), ('M3', 'M3'), ('M4', 'M4')], max_length=30),
        ),
    ]
