# Generated by Django 5.2.5 on 2025-08-19 04:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("insurance", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="insuredperson",
            name="age",
            field=models.PositiveSmallIntegerField(
                blank=True, help_text="When the date of birth is set, the age is calculated automatically.", null=True
            ),
        ),
    ]
