# Generated by Django 5.2.5 on 2025-08-19 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0002_alter_insuredperson_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
