# Generated by Django 5.2.6 on 2025-09-22 14:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("insurance", "0004_fix_empty_scheduled_messages"),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="broker",
            field=models.CharField(
                choices=[("christina-weber", "Christina Weber"), ("seamus-wolf", "Seamus Wolf")],
                default="seamus-wolf",
                max_length=30,
            ),
        ),
    ]
