# Generated by Django 5.2.6 on 2025-09-25 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0005_case_broker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outcome',
            name='case',
        ),
        migrations.RemoveField(
            model_name='case',
            name='status',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Outcome',
        ),
    ]
