# Generated by Django 5.2.6 on 2025-09-25 14:39

from django.db import migrations, models


def merge_first_last_name(apps, schema_editor):
    InsuredPerson = apps.get_model("insurance", "InsuredPerson")
    for person in InsuredPerson.objects.all():
        person.name = " ".join([person.first_name, person.last_name]).strip()
        person.save(update_fields=["name"])


class Migration(migrations.Migration):
    dependencies = [
        ("insurance", "0006_remove_outcome_case_remove_case_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="InsuredPerson",
            name="name",
            field=models.CharField(max_length=100, blank=True),
        ),
        migrations.RunPython(merge_first_last_name, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name="InsuredPerson",
            name="name",
            field=models.CharField(max_length=100, blank=False),
        ),
        migrations.RemoveField(
            model_name="InsuredPerson",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="InsuredPerson",
            name="last_name",
        ),
    ]
