# Generated by Django 5.2.6 on 2025-09-25 15:07

from django.db import migrations, models
import re


def merge_insured_persons_into_case(apps, schema_editor):
    Case = apps.get_model("insurance", "Case")
    for case in Case.objects.all():
        person = case.insured_persons.first()
        case.age = person.age
        case.income = person.income
        case.is_married = person.is_married
        case.name = person.name
        case.occupation = person.occupation

        match = re.search(r"I have (\d+) child", case.notes)
        if match:
            case.children_count = int(match.group(1))
        elif "I don't have children" in case.notes:
            case.children_count = 0

        if "I am applying for a visa" in case.notes:
            case.is_applying_for_first_visa = True

        if "I have German public health insurance" in case.notes:
            case.has_german_public_insurance = True

        if "I have public health insurance in another EU country" in case.notes:
            case.has_eu_public_insurance = True

        case.save()


class Migration(migrations.Migration):
    dependencies = [
        ("insurance", "0008_remove_insuredperson_date_of_birth_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="case",
            name="phone",
        ),
        migrations.RemoveField(
            model_name="case",
            name="whatsapp",
        ),
        migrations.AddField(
            model_name="case",
            name="age",
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="case",
            name="children_count",
            field=models.PositiveSmallIntegerField(blank=True, null=True, default=None),
        ),
        migrations.AddField(
            model_name="case",
            name="income",
            field=models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name="Yearly income"),
        ),
        migrations.AddField(
            model_name="case",
            name="is_married",
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="case",
            name="is_applying_for_first_visa",
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="case",
            name="has_german_public_insurance",
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="case",
            name="has_eu_public_insurance",
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="case",
            name="name",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="case",
            name="occupation",
            field=models.CharField(
                choices=[
                    ("employee", "Employee"),
                    ("azubi", "Azubi"),
                    ("studentEmployee", "Student (working)"),
                    ("studentSelfEmployed", "Student (self-employed)"),
                    ("studentUnemployed", "Student (unemployed)"),
                    ("selfEmployed", "Self-employed"),
                    ("unemployed", "Unemployed"),
                    ("other", "Other/unknown"),
                ],
                default="other",
                max_length=50,
            ),
        ),
        migrations.RunPython(merge_insured_persons_into_case),
        migrations.DeleteModel(
            name="InsuredPerson",
        ),
    ]
