# Generated by Django 5.2.7 on 2025-10-19 12:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("insurance", "0010_alter_case_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="case",
            name="notes",
            field=models.TextField(
                blank=True, help_text="For future notes, add Updates to the Case.", verbose_name="Question"
            ),
        ),
    ]
