# Generated by Django 5.2.7 on 2025-10-19 13:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("insurance", "0011_alter_case_notes"),
    ]

    operations = [
        migrations.RenameField(
            model_name="case",
            old_name="notes",
            new_name="question",
        ),
        migrations.AlterField(
            model_name="case",
            name="question",
            field=models.TextField("Question", blank=True),
        ),
    ]
