# Generated by Django 5.2.7 on 2025-10-27 12:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("insurance", "0012_rename_case_notes_to_question"),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="intent",
            field=models.CharField(
                choices=[
                    ("general", "General question"),
                    ("private", "Choose private health insurance"),
                    ("public", "Choose public health insurance"),
                    ("expat", "Choose expat health insurance"),
                ],
                default="general",
                max_length=50,
            ),
        ),
    ]
